### ISSUE TITLE
Error in updateTableData()

### ISSUE THREAD

**Issue by JuanDiegoLopez** [stewythe1st/AODV-Matlab#1]
Hi, I downloaded the code, but when I want to run, its throwing me an error in the updateTableData() function.
The specific error is "Array indices must be positive integers or logical values." in this line code: 
```tables(numel(tables)-i+1).Data = table2cell(data);```

Thanks for your answer.

**Comment by stewythe1st** [comment]
Hey Juan! To be honest, I didn't really expect anyone to get much use out of this. It';s just one of my old class projects. But I can certainly try my best to help you out here. I cloned the repo and was able to run it just fine. Can you tell me the exact steps you take to reproduce the error? Also what version of MATLAB are you using?

**Comment by JuanDiegoLopez** [comment]
I dont know what happened when I ran the code for first time, but now it's working fine. Thanks for your answer.
